site_name: HamsterBear
site_url: https://embeddedboys.github.io/HamsterBear/
site_description: offical site of HamsterBear
site_author: IotaHydrae

repo_url: https://github.com/embeddedboys/HamsterBear
edit_uri: edit/main/docs/docs/

theme:
  name: null
  custom_dir: 'cinder'
  # name: material
  locale: en

nav:
    - 主页: index.md
    - '用户向导':
      - '快速上手': howtouse.md
    - 使用文档:
      - '硬件文档': howtouse.md
      - '软件文档': howtouse.md
    - 关于: 
        - '作者': authors.md
        - '许可证': license.md
        - '发行说明': releasenote.md
